# Generated by Django 5.2.4 on 2025-07-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animals', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('habitat', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('size', models.CharField(blank=True, max_length=50)),
                ('diet', models.CharField(blank=True, max_length=100)),
                ('lifespan', models.CharField(blank=True, max_length=50)),
                ('facts', models.JSONField(default=list)),
                ('conservation_status', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='animal_images/')),
            ],
        ),
    ]
